let startBtn = document.getElementById('start'),
    val = document.querySelectorAll("div[class$='-value']"),
    inp = document.querySelectorAll('.expenses-item'),
    btns = document.getElementsByTagName('button'),
    approveBtn = [btns[0], btns[1]],
    calculateBtn = btns[2],
    inpOpt = document.querySelectorAll('.optionalexpenses-item'),
    inc = document.querySelector('#income'),
    chBox = document.querySelector('#savings'),
    sum = document.querySelector('#sum'),
    percent = document.querySelector('#percent'),
    year = document.querySelector('.year-value'),
    mounth = document.querySelector('.month-value'),
    day = document.querySelector('.day-value');